apiVersion: v1
kind: Service
metadata:
  name: {{ include "axionvera-node.fullname" . }}
  labels:
    {{ include "axionvera-node.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "axionvera-node.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: rpc
      port: {{ .Values.service.ports.rpc }}
      targetPort: rpc
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.ports.p2p }}
      targetPort: p2p
      protocol: TCP
{{- if .Values.service.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "axionvera-node.fullname" .) }}
  labels:
    {{ include "axionvera-node.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "axionvera-node.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
{{- end }}
